# Site settings
title: PMV DMV Services
email: VeltriP429@gmail.com
description: "Maintain and secure license plates at your convenience"
baseurl: ""
url: "http://pmvdmvservices.com"

# Build settings
markdown: kramdown
permalink: pretty

# Sass
sass:
    sass_dir: _sass
    style: compressed
